version: "3.8"

services:
  app:
    image: paulman176/my-app:latest
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    environment:
      - DSTACK_SIMULATOR_ENDPOINT=/tmp/tappd.sock
      - TEE_ENABLED=true
      - TEE_PRIVATE_KEY=18774cdb05b2470b8773856c7caea4ba23f459831ed8a27c68549cfe42a568a1
      - RPC_URL=https://base-sepolia.g.alchemy.com/v2/6gbfHkcrH1gSsMG8dQYbCK7WPtA1oNBy
      - CONFIDEX_CONTRACT=0x8f5E5B9282893F2A9CAE19569Be525Cf22a44AbE
      - PHALA_API_KEY=phak_ecybcnXK7gH-isnlrmhNMW-Ihcnkcn4dE_ynl2-GrLE
    depends_on:
      - tee-simulator

  tee-simulator:
    image: leechael/tappd-simulator:latest
    volumes:
      - /tmp/tappd.sock:/tmp/tappd.sock
    command: -l unix:/tmp/tappd.sock
